AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

plugins:
  - rubocop-rake
  - rubocop-rspec
